name: elegant_theme
description: Elegant theme is an awesome way to Beautify your Flutter Application.
version: 0.0.3
homepage:
repository: https://github.com/agradiance/elegant_theme

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
