name: elegant_theme
description: Elegant theme is an awesome way to Beautify your Flutter Application.
version: 0.1.0 #previous version 0.0.9
homepage:
repository: https://github.com/agradiance/elegant_theme

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flex_color_scheme: ^8.1.0
  flutter:
    sdk: flutter
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
