name: elegant_theme
description: Elegant theme is an awesome way to Beautify your Flutter Application.
version: 0.0.6 #previous version 0.0.5
homepage:
repository: https://github.com/agradiance/elegant_theme

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
